### ISSUE TITLE
Compatibility with webpack

### ISSUE THREAD

**Issue by Offirmo** [umdjs/umd#123]
The UMD template from here https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js is not consumed properly in webpack 2.

See my S/O question here: https://stackoverflow.com/questions/45929231/how-to-consume-an-umd-module-with-webpack

I suggested an improvement to the UMD template. What do you think?

**Comment by bonebizz21** [comment]
Thank

**Comment by SimonHeimberg** [comment]
did maybe #125 fix this issue as well? (It uses `self` if it exists and `this` else)

Your work around simply skips defining the global object if the root object does not exist.
So maybe you could use the UMD template https://github.com/umdjs/umd/blob/master/templates/returnExports.js which only defines the global when used in the browser.

**Comment by Offirmo** [comment]
Wow thanks for the answer!
However it was in 2017 and webpack 2 is long gone.
I'll close this issue, anyone experiencing a similar problem is welcome to open a new one.
