### ISSUE TITLE
Explicit code license

### ISSUE THREAD

**Issue by pgriess** [umdjs/umd#50]
It's unclear what the license is for these code snippets. My very limited understanding of copyright law suggests that source code without a license implies a copyright by the author and does not allow sharing / modifications / distribution / etc.

I would love to use these patterns, but am hesitant to do so until I understand the IP implications. It would  be great if the example source files had a license header, if there was a `LICENSE` file, `README.md` was updated, or similar.

**Comment by dlebedynskyi** [comment]
Look good in my opinion.

**Comment by arthurvr** [comment]
This issue can be closed I believe?

**Comment by addyosmani** [comment]
Yep. Thanks!
