### ISSUE TITLE
Sharing instances of jQuery and packaging just extensions in CommonJS

### ISSUE THREAD

**Issue by EvanCarroll** [umdjs/umd#68]
jQuery-plugin should provide a paradigm that shares instances of jQuery. It currently doesn't. If I want to share one instance of jQuery and have multiple different CommonJS-packaged extensions to it, we should be able to make that work.

This problem is pervasive. It affects at least two projects I'm working on now: DataTables and Notify.js. My suggestion is to have the jQuery plugin look like this..

    require('jQuery-plugin-foo')(window, [$]);

where

    require('jQuery-plugin-foo')(window, $); // extends $
    require('jQuery-plugin-foo')(window); // creates a jQuery object from the provided window.

If an instance of jQuery is provided the plugin gets that instance rather than creating its own in the UMD code. As for adding `window`, why not? It's explicit, but we can always satisfy this signature easily. Further, where window is not native (like under Node) it permits the user to provide something like jsdom. Ideas?

**Comment by lockyluchiano** [comment]
1
